### ISSUE TITLE
 invalid key是什么意思

### ISSUE THREAD

**Issue by briteming** [xutianyi1999/mutsuki#1]
hi.

root@racknerd-7b97d8:~# ~/mutsuki-by-xutianyi1999/target/release/mutsuki ~/mutsuki-by-xutianyi1999/target/release/config.json
[Console] 2022-07-09 10:26:17 - ERROR - 0.0.0.0:10810 -> invalid key
[Console] 2022-07-09 10:26:17 - ERROR - 0.0.0.0:10810 crashed
root@racknerd-7b97d8:~#

我今天采用acme.sh成功申请了我的域名的证书和key文件，不可能key文件是‘invalid key’啊。

之前使用一直正常。多谢回复

**Comment by xutianyi1999** [comment]
试试用X.509格式的证书，一些证书格式不支持

**Comment by briteming** [comment]
hi.

X.509格式的证书是什么格式？用acme.sh申请的证书不就是X.509格式的吗？
我是利用你这个程序搞了个https proxy, 之前使用一直正常, 一直可用来翻wall, 今天突然不正常了，是可执行文件mutsuki能自动更新? 而你今天做了什么更新吗

**Comment by xutianyi1999** [comment]
不会自己更新，你之前一直正常的话，看看你私钥文件是不是被修改过

**Comment by xutianyi1999** [comment]
使用PKCS8签名格式试试，你要使用其他格式的话可以自己修改代码
https://github.com/xutianyi1999/mutsuki/blob/d60365dee0e94a04f3b01871e11fe76ef8b5f756/src/common.rs#L81
https://github.com/rustls/pemfile/blob/e4559fe301a8e0b8504c8704a22326c6418c6382/src/pemfile.rs#L7-L19

**Comment by briteming** [comment]
hi.

可否考虑搞另外一个branch，用回4月9号的代码？我是那天搭建了https proxy,一直正常用到今天。
我用好几个程序搭建过https proxy，申请证书都是用acme.sh申请的，使用那些https proxy，从未遇到过‘invalid key’这样的提示。
非常感谢你。
看你的仓库，没看见你今天有改过仓库里面的代码，始终不明白怎么会遇到‘invalid key’这样的提示，匪夷所思。

**Comment by xutianyi1999** [comment]
你可以git checkout "commit hash"切到某一提交。

我使用它生成自签证书都是没问题的
https://github.com/xutianyi1999/key-generator

key-generator pem "domain name"

**Comment by briteming** [comment]
hi.

我这样搭建的mutsuki：
 登录Linux vps.
首先安装rust环境。
git clone https://github.com/xutianyi1999/mutsuki mutsuki-by-xutianyi1999
cd mutsuki-by-xutianyi1999
cargo build --release
稍等，在当前目录下，会生成target目录，
cd target/release
root@racknerd-7b97d8:~/mutsuki-by-xutianyi1999/target/release# ls
build  deps  examples  incremental  mutsuki  mutsuki.d
root@racknerd-7b97d8:~/mutsuki-by-xutianyi1999/target/release# cp ~/mutsuki-by-xutianyi1999/cfg-example/config.json ./
root@racknerd-7b97d8:~/mutsuki-by-xutianyi1999/target/release# ls
build  config.json  deps  examples  incremental  mutsuki  mutsuki.d
root@racknerd-7b97d8:~/mutsuki-by-xutianyi1999/target/release# nano config.json
root@racknerd-7b97d8:~/mutsuki-by-xutianyi1999/target/release# cat config.json
[
  {
    "protocol": "https",
    "bind_addr": "0.0.0.0:10800",
    "server_cert_key": {
      "cert_path": "/etc/letsencrypt/live/mydomain.com/fullchain.pem",
      "priv_key_path": "/etc/letsencrypt/live/mydomain.com/privkey.pem"
    }
}
]
root@racknerd-7b97d8:~/mutsuki-by-xutianyi1999/target/release# ./mutsuki config.json

不过命令./mutsuki config.json是运行在前台的，我们可以利用systemd把它运行为service:
nano /etc/systemd/system/mutsuki.service
cat /etc/systemd/system/mutsuki.service
显示：
[Unit]
After=network.target

[Service]
WorkingDirectory=/root/mutsuki-by-xutianyi1999/target/release/
ExecStart=/root/mutsuki-by-xutianyi1999/target/release/mutsuki /root/mutsuki-by-xutianyi1999/target/release/config.json
Restart=always

[Install]
WantedBy=multi-user.target

然后，
systemctl start mutsuki

systemctl enable mutsuki
服务器端搭建完成。

然后在客户端机器mac或windows上的chrome浏览器的switchy omega插件里设置https proxy,地址为mydomain.com ,
端口为10800 ，浏览器即可翻墙。


我在4月9日就是如上安装的，谁知到了7月9日就不行了。
上面我哪里搞错了吗

**Comment by xutianyi1999** [comment]
没有，你可以试我给的样例配置，都是正常运行的

**Comment by briteming** [comment]
hi.
我今天还用项目nadoo/glider安装了https proxy, 搭配的证书和私匙就是之前搭配给mutsuki所用的证书和私匙，这说明我的域名的
证书和私匙是没有问题的，就是不明白怎么昨天（7月9日）开始突然不行了，提示invalid key呢？

**Comment by xutianyi1999** [comment]
support EC, PKCS8, RSA   46c46298a529869e8d83681f6de8ef15d9886e31

**Comment by briteming** [comment]
哦，现在OK了。
之前显示 invalid key的提示时，用acme.sh/certbot生成的私钥匙的格式都是rsa格式，对吗？而编译出来的mutsuki只认pkcs8格式的私钥匙，不认rsa格式。所以，在之前显示 invalid key的提示时，把私钥匙的格式由rsa格式转换为pkcs8格式，即可解决问题，对吗？但我4月9日编译出来的mutsuki怎么又认rsa格式的私钥匙呢？

**Comment by xutianyi1999** [comment]
https://github.com/rustls/pemfile/blob/e4559fe301a8e0b8504c8704a22326c6418c6382/src/pemfile.rs#L22-L29
只有标头区别，直接改标头也行

**Comment by briteming** [comment]
hi.

不过，我的https proxy地址：mydomain.com:10800也是可能被扫描软件扫出来的吧？所以可否考虑添加用户名/密码认证呢？

**Comment by xutianyi1999** [comment]
支持tls双向认证和http账户认证，如何使用看配置代码
